### ISSUE TITLE
Shared instance of JsonSerializerSettings

### ISSUE THREAD

**Issue by Anlo2846** [JohanLarsson/Gu.Settings#27]
Two constructors of JsonRepositorySettings sets the property JsonSerializerSettings to the static instance JsonRepositorySettings.DefaultJsonSettings.

When two different repositories are created in parallel using those constructors, they will share the static instance and any changes to the JsonSerializerSettings object will affect both repositories.

**Comment by JohanLarsson** [comment]
Thanks for reporting!
